db:
  image: postgres
  environment:
    - POSTGRES_USER=gissmo
    - POSTGRES_PASSWORD=gissmo
  ports:
    - "5434:5432"
web:
  extends:
    file: common.yml
    service: webapp
  command: python manage.py runserver 0.0.0.0:8000
  links:
    - db
  environment:
    - DJANGO_SETTINGS_MODULE=gissmo.settings.dev
